In [27]:
# 라이브러리 불러오기
import pandas as pd
import seaborn as sns

# # titanic 데이터셋 로딩
titanic = sns.load_dataset('titanic').rename(columns={'sex':'gender'})

# # 행 인덱스 0~9 범위에서 age, fare 2개 열을 선택하여 데이터프레임 만들기
# df = titanic.loc[0:9, ['age','fare']]

# # 데이터프레임 출력
# df

In [28]:
# 조건식 적용 (20세 미만: age < 20)
titanic['age'] < 20

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [29]:
# 불린 인덱싱 (20세 미만의 조건을 충족하는 행을 필터링)
titanic_under20 = titanic[ titanic['age'] < 20 ]
titanic_under20 = titanic_under20.rename(columns={'sex':'gender'})
titanic_under20[titanic_under20['gender'] == 'female'].head(3)

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True

In [30]:
# 불린 인덱싱 (loc 인덱서 활용)
titanic.loc[titanic['age'] < 20].head(3)

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False

In [31]:
# 불린 인덱싱 (NOT 논리연산)
titanic.loc[~(titanic['age'] < 20)].head(3)   # not

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [32]:
# 나이가 10대(10~19세)인 승객 (AND 논리연산)
mask1 = (titanic.age >= 10) & (titanic.age < 20)
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [33]:
# 나이가 10세 미만(0~9세)이고 여성인 승객 (AND 논리연산, loc 인덱서)
mask2 = (titanic.age < 10) & (titanic.gender == 'female')
df_female_under10 = titanic.loc[mask2]
df_female_under10.head()

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.0,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False

In [ ]:
# 나이가 10세 미만(0~9세) 또는 60세 이상인 승객 (OR 논리연산)
# age, sex, alone 열만 선택 (loc 인덱서, fancy indexing)
mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3, ['age', 'gender', 'alone']]
df_under10_morethan60.head()

KeyError: "['sex'] not in index"

In [ ]:
# 불린 시리즈를 새로운 열로 추가
titanic['age_under_20'] = titanic['age'] < 20
titanic.head(3)

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_under_20
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,False